---
abstract: 'perl interface to NetBox API'
author:
  - 'Volodymyr Pidgornyi <vp@dtel-ix.net>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: NetBox-API
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: '0'
resources:
  repository: https://github.com/kornix/perl-NetBox-API.git
version: v0.1.3
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
